version: '3'
services:

  news_spider:
    build:
      context: .
      dockerfile: news_spider/Dockerfile
    image: news_spider
    container_name: news_spider
    env_file:
      - .env
    restart: unless-stopped
    tty: True
    working_dir: /news_spider

  spider_news_mongo:
    image: mongo
    container_name: spider_news_mongo
    volumes:
      - mongodb:/data/db
    restart: unless-stopped
    tty: True

  news_spider_api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: news_spider_api
    container_name: news_spider_api
    env_file:
      - .env
    ports:
      - "0.0.0.0:5001:5001"
    restart: unless-stopped
    tty: True
    working_dir: /api

volumes:
  mongodb: