version: "3.3"
services:

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    image: news_spider_bot
    container_name: news_spider_bot
    env_file:
      - .env
    restart: always
    tty: True
    working_dir: /bot

  news_spider:
    build:
      context: .
      dockerfile: news_spider/Dockerfile
    image: news_spider
    container_name: news_spider
    env_file:
      - .env
    volumes:
      - ${LOGS_PATH}:${LOGS_PATH}
    restart: unless-stopped
    tty: True
    working_dir: /news_spider
    deploy:
      resources:
        limits:
          cpus: '3.25'
          memory: 5gb

  spider_news_mongo:
    image: mongo
    container_name: spider_news_mongo
    volumes:
      - /opt/disk/news_spider_mongo:/data/db
    restart: unless-stopped
    tty: True
    deploy:
      resources:
        limits:
          cpus: '5.25'
          memory: 10gb

  news_spider_api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: news_spider_api
    container_name: news_spider_api
    env_file:
      - .env
    ports:
      - "0.0.0.0:5001:5001"
    restart: unless-stopped
    tty: True
    working_dir: /api
